CREATE DATABASE DBL;
USE DBL;
CREATE TABLE STUDENTS(ROLL_NO INT, SNAME VARCHAR(20), BRANCH VARCHAR(10));
INSERT INTO STUDENTS VALUES (1,"SURYA","CSE"),(2,"ADITHYAA","AIML"),(3,"VIKRAM","ECE");
SELECT * FROM STUDENTS;
